# Generated by Django 2.0.10 on 2019-12-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
